name: Multi-OS Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      # Common steps for all OSes
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Common step 2
        run: echo "This step runs on all OSes"

      # OS-specific steps
      - name: Run Linux commands
        if: runner.os == 'Linux'
        uses: docker/run-action@v2
        with:
          image: your-docker-image  # Replace with your Docker image
          options: --entrypoint /bin/sh
          args: -c "your linux commands here" # Replace with your commands

      - name: Run macOS commands
        if: runner.os == 'macOS'
        run: |
          brew update  # Example macOS command
          brew install your-package  # Example macOS command

      - name: Run Windows commands
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          choco install your-package -y  # Example Windows command
          # More Windows commands here

      # More common steps after OS-specific actions
      - name: Common step 3
        run: echo "This step also runs on all OSes after OS-specific steps"